import Foundation

struct PresetBuilder {
    static let policyGroups = [
        "Claude Code",
        "OpenAI",
        "Gemini",
        "Binance",
        "OKX",
        "Bybit",
        "YouTube",
        "Netflix",
        "Other"
    ]

    static let ruleFiles = [
        "cn_direct_domains.list",
        "cn_direct_ip.list",
        "claude_code.list",
        "openai.list",
        "gemini.list",
        "binance.list",
        "okx.list",
        "bybit.list",
        "youtube.list",
        "netflix.list"
    ]

    func buildExternalConfig(at destination: URL) throws {
        let content = """
        version = 1
        [custom]
        enable_rule_generator = false
        overwrite_original_rules = false

        # This preset file is generated by SubConfigStudio.
        # The macOS app assembles proxy groups and rules locally after
        # fetching merged proxies from subconverter.
        """

        try content.write(to: destination, atomically: true, encoding: .utf8)
    }

    func loadRuleLines(from rulesDirectory: URL) throws -> [String] {
        var lines: [String] = []
        for file in Self.ruleFiles {
            let fileURL = rulesDirectory.appendingPathComponent(file)
            let content = try String(contentsOf: fileURL, encoding: .utf8)
            let fileLines = content
                .split(whereSeparator: \.isNewline)
                .map { String($0).trimmingCharacters(in: .whitespaces) }
                .filter { !$0.isEmpty && !$0.hasPrefix("#") }
            lines.append(contentsOf: fileLines)
        }

        return lines + ["MATCH,Other"]
    }
}
