import Foundation

struct PresetBuilder {
    static let policyGroups = [
        "Claude Code",
        "OpenAI",
        "Gemini",
        "Binance",
        "OKX",
        "Bybit",
        "Futu",
        "Lark",
        "GitHub",
        "Telegram",
        "X",
        "Apple",
        "YouTube",
        "Google",
        "Netflix",
        "Steam",
        "Supercell",
        "Other"
    ]

    /// Other 是 MATCH 的目标,不能停用:MATCH 指向一个不存在的策略组会让 mihomo
    /// 拒绝加载整份配置。UI 侧也不给它开关。
    static let alwaysEnabledPolicyGroups: Set<String> = ["Other"]

    /// 实际会被写进产物的策略组。停用集合由用户维护,这里是唯一的裁决点 ——
    /// 组的渲染和规则的过滤都要走它,否则两边会漂移出「规则指向已删除的组」。
    static func enabledPolicyGroups(disabled: Set<String>) -> [String] {
        policyGroups.filter { alwaysEnabledPolicyGroups.contains($0) || !disabled.contains($0) }
    }

    // Service rules that must take precedence over the built-in CN direct
    // rules. Futu (富途牛牛) domains are otherwise swallowed by
    // RULE-SET,cn-domain / GEOSITE,cn and forced to DIRECT, so they have to
    // be evaluated before the CN block.
    static let priorityServiceRuleFiles = [
        "futu.list",
        "lark.list"
    ]

    static let builtinDirectRuleFiles = [
        "cn_direct_domains.list",
        "cn_direct_ip.list"
    ]

    static let serviceRuleFiles = [
        "claude_code.list",
        "openai.list",
        "gemini.list",
        "binance.list",
        "okx.list",
        "bybit.list",
        "github.list",
        "telegram.list",
        "x.list",
        "apple.list",
        "youtube.list",
        "google.list",
        "netflix.list",
        "steam.list",
        "supercell.list"
    ]

    func buildExternalConfig(at destination: URL) throws {
        let content = """
        version = 1
        [custom]
        enable_rule_generator = false
        overwrite_original_rules = false

        # This preset file is generated by clashconvert.
        # The macOS app assembles proxy groups and rules locally after
        # fetching merged proxies from subconverter.
        """

        try content.write(to: destination, atomically: true, encoding: .utf8)
    }

    func loadRuleLines(
        from rulesDirectory: URL,
        customDirectRulesText: String = "",
        disabledPolicyGroups: Set<String> = []
    ) throws -> [String] {
        let priorityServiceRules = try loadRuleLines(from: Self.priorityServiceRuleFiles, in: rulesDirectory)
        let builtinDirectRules = try loadRuleLines(from: Self.builtinDirectRuleFiles, in: rulesDirectory)
        let customDirectRules = try normalizeCustomDirectRules(from: customDirectRulesText)
        let serviceRules = try loadRuleLines(from: Self.serviceRuleFiles, in: rulesDirectory)

        let all = priorityServiceRules + builtinDirectRules + customDirectRules + serviceRules + ["MATCH,Other"]
        let dropped = Set(Self.policyGroups).subtracting(Self.enabledPolicyGroups(disabled: disabledPolicyGroups))
        guard !dropped.isEmpty else {
            return all
        }

        // 停用的组,指向它的规则必须一并丢掉,否则 mihomo 因为目标组不存在而拒绝
        // 加载整份配置。这类流量随之落到 MATCH,Other。
        return all.filter { line in
            guard let target = Self.ruleTarget(of: line) else { return true }
            return !dropped.contains(target)
        }
    }

    /// 取一条 Clash 规则的目标策略组。
    ///
    /// 不能简单取最后一段:`GEOIP,cn,DIRECT,no-resolve` 的末段是修饰符。目标固定在
    /// 第 3 段,只有无参数的 `MATCH` 在第 2 段。
    static func ruleTarget(of line: String) -> String? {
        let parts = line.split(separator: ",").map { $0.trimmingCharacters(in: .whitespaces) }
        guard let type = parts.first else { return nil }
        let targetIndex = type == "MATCH" ? 1 : 2
        guard parts.count > targetIndex else { return nil }
        return parts[targetIndex]
    }

    private func loadRuleLines(from files: [String], in rulesDirectory: URL) throws -> [String] {
        var lines: [String] = []
        for file in files {
            let fileURL = rulesDirectory.appendingPathComponent(file)
            let content = try String(contentsOf: fileURL, encoding: .utf8)
            let fileLines = content
                .split(whereSeparator: \.isNewline)
                .map { String($0).trimmingCharacters(in: .whitespaces) }
                .filter { !$0.isEmpty && !$0.hasPrefix("#") && !$0.hasPrefix("//") }
            lines.append(contentsOf: fileLines)
        }

        return lines
    }

    private func normalizeCustomDirectRules(from rawText: String) throws -> [String] {
        var normalized: [String] = []
        var seen = Set<String>()

        for rawLine in rawText.split(whereSeparator: \.isNewline) {
            let line = String(rawLine).trimmingCharacters(in: .whitespacesAndNewlines)
            guard !line.isEmpty, !line.hasPrefix("#"), !line.hasPrefix("//") else {
                continue
            }

            let normalizedLine = try normalizeCustomDirectRule(line)
            guard seen.insert(normalizedLine).inserted else {
                continue
            }
            normalized.append(normalizedLine)
        }

        return normalized
    }

    private func normalizeCustomDirectRule(_ line: String) throws -> String {
        if !line.contains(",") {
            guard isValidBareDomain(line) else {
                throw PresetBuilderError.invalidCustomDirectRule(line)
            }
            return "DOMAIN-SUFFIX,\(line),DIRECT"
        }

        let segments = line.split(separator: ",", omittingEmptySubsequences: false).map {
            $0.trimmingCharacters(in: .whitespaces)
        }
        guard segments.count >= 2 else {
            throw PresetBuilderError.invalidCustomDirectRule(line)
        }

        let ruleType = segments[0].uppercased()
        guard Self.supportedCustomRuleTypes.contains(ruleType), !segments[1].isEmpty else {
            throw PresetBuilderError.invalidCustomDirectRule(line)
        }

        if segments.count == 2 {
            return "\(ruleType),\(segments[1]),DIRECT"
        }

        guard segments[2].uppercased() == "DIRECT" else {
            throw PresetBuilderError.invalidCustomDirectRule(line)
        }

        return ([ruleType] + Array(segments.dropFirst())).joined(separator: ",")
    }

    private func isValidBareDomain(_ line: String) -> Bool {
        !line.isEmpty
            && !line.contains(" ")
            && !line.contains("/")
            && !line.contains(":")
            && !line.hasPrefix(".")
            && !line.hasSuffix(".")
    }

    private static let supportedCustomRuleTypes: Set<String> = [
        "DOMAIN",
        "DOMAIN-SUFFIX",
        "DOMAIN-KEYWORD"
    ]
}

enum PresetBuilderError: LocalizedError {
    case invalidCustomDirectRule(String)

    var errorDescription: String? {
        switch self {
        case .invalidCustomDirectRule(let line):
            return "Invalid direct-domain rule: \(line). Use a bare domain or a DOMAIN/DOMAIN-SUFFIX/DOMAIN-KEYWORD rule that ends with DIRECT."
        }
    }
}
